### ISSUE TITLE
Prevent "improper store..." error - UTF8TextConverter

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swa-teaching/Scamper#171]
As a user I want to visit hpi.de without getting an error message

predict: 40

Acceptance Criteria:

- [x]  Error should be clearly identified
- [x]  hpi.de should load

**Comment by konstantinjdobler** [comment]
This error is caused in the `UTF8TextConverter decodeString:` method. The problem is that `self nextFromStream: readStream` sometimes reads more than one character which causes the improper store error because the collection we store in only accepts single characters
