### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swa-teaching/Scamper#176]
As a user I want to visit https websites in order to be secure on the Internet

predicted: 40

Acceptance Criteria:

- [x]  HTTPS websites are available
- [x]  data transfers are secure

**Comment by mlichtblau** [comment]
Acceptance Criteria:

- [ ] HTTPS websites are available
- [ ] data transfers are secure

**Comment by konstantinjdobler** [comment]
It seems we already have HTTPS support. The error causing many sites, including HTTPS but not limited to, seems to be another one. https://www.google.de/intl/de/options/ is HTTPS but can be visited without an error message.
