### ISSUE TITLE
CSS: Link color

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swa-teaching/Scamper#182]
As a user I want to see links in the right color in order to notice them.

Acceptance Criteria:
- [x] Links on en.wikipedia.org should be blue

**Comment by konstantinjdobler** [comment]
We suspect the link color is parsed correctly, wikipedia just delivers them in white to us or something is wrong in the downloading process. Possible fix: when parsing the document, if we have a DOMNode that is a link, automatically set the color to blue. This is not nice, and makes links in other colors impossible.

**Comment by leonardlang** [comment]
The link color ist white, if we access a wikipedia site through Google.
It is parsed correctly, if we call the wikipedia site directly with the URL or through wikipedia.org.

**Comment by konstantinjdobler** [comment]
Fixed now by correctly loading all stylesheets.
