### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by kris-fillip** [hpi-swa-teaching/Scamper#198]
As a developer I want my tests to run through.
Due to the new feature homepage test01jumpToRelativeUrl and test04testRealWorldCookies are currently broken when using homepages differing from browse:start or browse:about.

- [x] test01jumpToRelativeUrl runs through
- [x] test04testRealWorldCookies runs through

**Comment by konstantinjdobler** [comment]
Integrate you results in the new refactored test classes
