### ISSUE TITLE
Change the browser URL after a redirection

### ISSUE THREAD

**Issue by PFischbeck** [hpi-swa-teaching/Scamper#86]
> When visiting http://google.com/, when I search for something and click on any result, I don't want to get a redirection warning.

![redirection](https://cloud.githubusercontent.com/assets/2820802/3131218/1a8e8de0-e802-11e3-8b5c-39263a4881e6.png)

Estimated effort: 162

**Comment by konstantinjdobler** [comment]
Closed in #195
